"""Feed-only importer for leads generated by the SGML Marketing Pipeline.

WHAT THIS IS
------------
The marketing pipeline (a SEPARATE project) produces opt-ins — checklist
downloads and "Margin Leak Review" bookings — which are logged in a sheet
shaped like the marketing repo's ``docs/lead-log-template.csv``:

    Date, Name / Business, Source, Magnet, Stage, Est $/mo, Notes

This module reads a CSV exported from that sheet and creates ``Lead`` rows in
SGML Sales, tagged ``source="marketing-pipeline"`` so the funnel can be
attributed back to marketing.

READ-ONLY BOUNDARY
------------------
This is the SALES side of the integration. It only ever *reads* a CSV the
marketing world already produces. It NEVER writes to, imports from, or
otherwise modifies the ``SGML-Marketing-Pipeline`` project — that repository is
read-only to us. See ``docs/MARKETING-LEAD-IMPORT.md``.

NOTE ON "source"
----------------
Two different meanings of the word collide here, so be deliberate:

* The marketing log's ``Source`` column is the *channel* (instagram, linkedin…).
* SGML Sales' ``Lead.source`` is the *system of origin* — here always
  ``"marketing-pipeline"``. (Per-channel attribution would need a dedicated
  ``channel`` column on ``Lead``; that is a deliberate follow-up, not done here.)
"""

from __future__ import annotations

import argparse
import csv
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path
from typing import TextIO

from sqlmodel import Session, select

from ..core.enums import LeadStatus
from ..models import Lead

#: The value written to ``Lead.source`` for every lead this importer creates.
MARKETING_SOURCE = "marketing-pipeline"

#: Map the marketing log's free-text ``Stage`` onto our ``LeadStatus`` enum.
#: Unknown / early stages fall back to NEW (see ``_status_for``).
_STAGE_TO_STATUS: dict[str, LeadStatus] = {
    "lead": LeadStatus.NEW,
    "call-booked": LeadStatus.NEW,
    "call-done": LeadStatus.QUALIFIED,
    "proposal": LeadStatus.QUALIFIED,
    "client": LeadStatus.CONVERTED,
    "lost": LeadStatus.UNQUALIFIED,
}


@dataclass
class ImportResult:
    """Summary of an import run."""

    imported: int = 0
    skipped_duplicate: int = 0
    skipped_invalid: int = 0
    leads: list[Lead] = field(default_factory=list)

    def __str__(self) -> str:  # pragma: no cover - cosmetic
        return (
            f"imported={self.imported} "
            f"skipped_duplicate={self.skipped_duplicate} "
            f"skipped_invalid={self.skipped_invalid}"
        )


def _norm(value: str | None) -> str:
    """Lower-case, stripped — used for case-insensitive header/stage lookups."""
    return (value or "").strip().lower()


def _status_for(stage: str) -> LeadStatus:
    return _STAGE_TO_STATUS.get(_norm(stage), LeadStatus.NEW)


def _name_from(row: dict[str, str]) -> str:
    """Pull the lead's name from the row, tolerating header variations."""
    return (row.get("name / business") or row.get("name") or row.get("business") or "").strip()


def _is_placeholder(name: str) -> bool:
    """The shipped template carries one sample row meant to be deleted."""
    lowered = name.lower()
    return "delete this row" in lowered or lowered.startswith("example co")


def import_leads_from_rows(session: Session, rows: Iterable[dict[str, str]]) -> ImportResult:
    """Create marketing-pipeline leads from already-parsed CSV rows.

    Idempotent: a row is skipped if a ``marketing-pipeline`` lead with the same
    name already exists (in the DB or earlier in this same batch), so re-importing
    an updated export will not create duplicates.
    """
    result = ImportResult()

    # Names already tagged marketing-pipeline — the dedupe key. Seeded from the DB
    # and extended as we go so duplicates *within* one file are caught too.
    existing: set[str] = {
        (lead.name or "").lower()
        for lead in session.exec(select(Lead).where(Lead.source == MARKETING_SOURCE)).all()
    }

    for raw in rows:
        row = {_norm(k): v for k, v in raw.items()}
        name = _name_from(row)

        if not name or _is_placeholder(name):
            result.skipped_invalid += 1
            continue

        if name.lower() in existing:
            result.skipped_duplicate += 1
            continue

        lead = Lead(
            name=name,
            source=MARKETING_SOURCE,
            status=_status_for(row.get("stage", "")),
        )
        session.add(lead)
        existing.add(name.lower())
        result.leads.append(lead)
        result.imported += 1

    if result.imported:
        session.commit()
        for lead in result.leads:
            session.refresh(lead)

    return result


def import_leads_from_csv(session: Session, source: str | Path | TextIO) -> ImportResult:
    """Import leads from a marketing lead-log CSV (path or open text stream)."""
    if isinstance(source, str | Path):
        with Path(source).open(newline="", encoding="utf-8") as fh:
            return import_leads_from_rows(session, csv.DictReader(fh))
    return import_leads_from_rows(session, csv.DictReader(source))


def main(argv: list[str] | None = None) -> int:
    """CLI: ``python -m sgml_sales.services.marketing_import <leads.csv>``."""
    parser = argparse.ArgumentParser(
        description=(
            "Import leads from a CSV exported from the SGML Marketing Pipeline lead log "
            "into SGML Sales (tagged source='marketing-pipeline'). Read-only to the "
            "marketing project."
        )
    )
    parser.add_argument("csv_path", help="Path to the exported marketing lead-log CSV.")
    args = parser.parse_args(argv)

    # Imported lazily so the module stays importable (e.g. in tests) without
    # touching the application database/engine.
    from ..database import engine, init_db

    init_db()
    with Session(engine) as session:
        result = import_leads_from_csv(session, args.csv_path)

    print(f"Marketing lead import: {result}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
